controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    gravity_compensation_controller:
      type: trossen_arm_controllers/GravityCompensationController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

gravity_compensation_controller:
  ros__parameters:
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - left_carriage_joint
