name: build-and-test-jazzy

on:
  push:
    branches:
      - main
      - jazzy
  pull_request:
    branches:
      - main
      - jazzy
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          use-ros2-testing: true
          required-ros-distributions: jazzy
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: jazzy
          vcs-repo-file-url: dependencies.repos
          package-name: |
            trossen_arm_bringup
            trossen_arm_hardware
            trossen_arm_moveit
            trossen_arm_ros
